### ISSUE TITLE
What to use for SSH in Ruby today?

### ISSUE THREAD

**Issue by odigity** [mitchellh/libssh2-ruby#5]
I was inspired by your old post to go hunt down ruby bindings for libcurl and openssh to replace my current use of HTTParty and Net::SSH (which I'm disastisfied with):

http://mitchellh.com/abandoning-rubygems

However, while I did find the curb gem for HTTP, there still doesn't seem to be any maintained/working ruby bindings for any of the popular SSH libraries.

So, I'm curious -- what have you been using in the meantime?  And do you know of any recent work in this area by anyone?

**Comment by thedrow** [comment]
+1. I'm also interested to know.

**Comment by mitchellh** [comment]
I've been using Go full time since late 2012 and I also wrote an SSH library for that (until a more official Go one was released) and that's sort of what happened here. This is nothing negative about Ruby, I just moved away from it.
